CREATE TABLE IF NOT EXISTS dmd_staging.responsetap_full_call_records
(
  cdrid character varying(255),
  visitorid character varying(255),
  visitid character varying(255),
  locationformattedcustomernumber character varying(255),
  trackingnumber character varying(255),
  locationformattedtrackingnumber character varying(255),
  locationformattedbusinessnumber character varying(255),
  campaignname character varying(255),
  searchphrase character varying(255),a
  calldate numeric(15,0),
  callduration integer,
  calltalktime integer,
  disposition character varying(255),
  salesvalue character varying(255),
  leadvalue character varying(255),
  goalname character varying(255),
  goalvalue character varying(255),
  recorded boolean,
  sourceid character varying(255),
  channelname character varying(255),
  mediumname character varying(255),
  mediumtypename character varying(255),
  adreference character varying(255),
  landingpage text,
  referrer text,
  numbergroupid character varying(255),
  numbergroupname character varying(255),
  callid character varying(255),
  benchmarkviewedid character varying(255),
  benchmarklabel character varying(255),
  benchmarkdescription character varying(255),
  customvariables character varying(255),
  cookies character varying(255),
  currencysymbol character varying(255)
);
