CREATE TABLE IF NOT EXISTS dmd_staging.test_doubleclick_search_campaign
(
  date date,
  account character varying,
  campaign character varying,
  campaignid character varying,
  campaignstatus character varying,
  campaignlabels character varying,
  campaigntype character varying,
  effectivelabels character varying,
  avgcpc double precision,
  avgpos double precision,
  clicks double precision,
  cost double precision,
  ctr double precision,
  impr double precision,
  adwordsconversions double precision,
  adwordsconversionvalue double precision,
  visits integer,
  cpa double precision,
  aov double precision,
  calls integer,
  cmbs integer,
  uniquelands integer,
  revenue double precision,
  sales integer,
  storelocator integer,
  videochats integer,
  allconversions integer,
  searchimpressionshare character varying
)
